### ISSUE TITLE
Usage in electronJS throws an error which says: SaveToExistingDirectoryPlugin not a constructor

### ISSUE THREAD

**Issue by ProfNuru** [website-scraper/website-scraper-existing-directory#17]
I am using this in the main.js of an electron application.
My imports look like this:
`const scrape = (...args) => import('website-scraper').then(({default:scrape})=>scrape(...args));
const SaveToExistingDirectoryPlugin = (...args) => import('website-scraper-existing-directory').then(({default:SaveToExistingDirectoryPlugin})=>SaveToExistingDirectoryPlugin(...args));
`
My scrape options like this:
`let options = {
        urls: [url],
        directory: cache_dir,
        plugins: [ new SaveToExistingDirectoryPlugin() ]
    }`
Then I execute scrape with the options:
`scrape(options).then(...)`
This throws an error which says "SaveToExistingDirectoryPlugin is not a constructor"

How to resolve this

**Comment by s0ph1e** [comment]
Hi @ProfNuru 

Sorry for the late response. Unfortunately, I'm not familiar with electron details. 
Did you try to use it without the plugin? Or maybe use it exactly as [in the example in readme](https://github.com/website-scraper/website-scraper-existing-directory#usage)?
